### ISSUE TITLE
Erro 500 ao buscar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [LinikerSilva/spring-client-crud#1]
Olá Liniker, meu nome é Alexandre e estou corrigindo sua atividade.

Trabalho aceito, parabéns! Para ficar 100%, sugiro incluir o tratamento de exceções. Está retornando erro 500 quando o id não existe ao atualizar um cliente (PUT) e excluí-lo (DELETE).

Abraço e bons estudos

**Comment by linikersilva** [comment]
Olá! Agradeço pela correção!
Informo que corrigi este issue no commit "07d49af", conforme o link:
https://github.com/LinikerSilva/spring-client-crud/commit/07d49af5fbbec9028b65de128ed893edfef68703
